#deployment and service for mongo db
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
#        can change -name to something randomName
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
          - containerPort: 3000
#          putting the variable names in webbapp
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-passWord
          - name: USER_PWD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-passWord
          - name: DB_URL
#            to get value from mongo-config.yml use valueFrom (called configMapKeyRef)
            valueFrom:
              configMapKeyRef:
                name: mongo-configTut
                key: mongo-url


#random line as seen in video ex
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000